spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/solicitudes_BD
    username: admnin
    password: system123
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
