spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/solicitudes_db
    username: tu_usuario
    password: tu_contraseña
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
